#!/bin/ksh

function dolist {
  cat << EOF
xterm
chrome
EOF
}

ex=$(dolist | $HOME/DWM/dmenu-4.2.1/dmenu "$@")

case "$ex" in
  xterm) exec xterm ;;
  chrome) exec google-chrome ;;
  *) exec "$ex" ;;
esac

